const projectsData = [
    {
        id: "modal-1",
        number: "01",
        category: "main",
        title: "Automação de Performance com K6",
        summary: "Testes de carga, stress e spike para resiliência de APIs.",
        tags: ["K6", "Performance", "Stress Test"],
        tools: ["K6 (JavaScript)", "Grafana/InfluxDB", "CLI Automation"],
        desc: "Implementação de arquitetura de performance voltada diretamente à resiliência e estabilidade da infraestrutura. A aplicação dos testes engloba não apenas disparo cego de requisições, mas cenários hiper-realistas utilizando Load, Soak, Spike e Stress testing.<br><br>Foram desenvolvidos thresholds rígidos de validação para forçar o failover caso a latência p95 ultrapassasse os limites de SLA aceitáveis (500ms) ou a taxa de erros de chamadas superasse 1%. Essa arquitetura atua como a primeira barreira contra gargalos de produção.",
        code: `import http from 'k6/http';\nimport { check, sleep } from 'k6';\n\nexport const options = {\n  stages: [\n    { duration: '2m', target: 2000 },\n    { duration: '5m', target: 2000 },\n    { duration: '2m', target: 0 },\n  ],\n  thresholds: {\n    http_req_duration: ['p(95)<500'],\n    http_req_failed: ['rate<0.01'],\n  },\n};`,
        repo: "https://github.com/DouglasAntoni0/projeto-completo-k6",
        visualClass: "k6-bg",
        iconClass: "ph-gauge",
        reverseBorder: false
    },
    {
        id: "modal-2",
        number: "02",
        category: "main",
        title: "Web Testing E2E com Cypress",
        summary: "Framework ponta a ponta focado em robustez e CI/CD.",
        tags: ["Cypress", "E2E", "JavaScript"],
        tools: ["Cypress", "JavaScript", "GitHub Actions"],
        desc: "Projeto complexo integrando chamadas de API, banco de dados e UI. Criação de comandos customizados robustos para otimizar o tempo de execução e setup de massa de dados.",
        code: `Cypress.Commands.add('loginE2E', (email, password) => {\n  cy.session([email, password], () => {\n    cy.request('POST', '/api/auth', { email, password }).then((resp) => {\n      window.localStorage.setItem('token', resp.body.token);\n    });\n    cy.visit('/dashboard');\n    cy.get('[data-cy="user-menu"]').should('be.visible');\n  });\n});`,
        repo: "https://github.com/DouglasAntoni0/ninjadocypress",
        visualClass: "cypress-bg",
        iconClass: "ph-check-circle",
        reverseBorder: true
    },
    {
        id: "modal-3",
        number: "03",
        category: "main",
        title: "Playwright Avançado & CI/CD",
        summary: "Automação cross-browser paralela com Page Object Model.",
        tags: ["Playwright", "CI/CD", "POM"],
        tools: ["Playwright Test", "Page Object Model", "GitHub Actions"],
        desc: "Automação cross-browser configurada para paralelismo extremo usando o poder do motor do ecossistema Playwright. O projeto adota estritamente o paradigma Page Object Model (POM) garantindo manutenção isolada e clara.<br><br>Foram desenhadas asserções dinâmicas de alta confiabilidade (auto-waiting e expect patterns), em conjunto com a interceptação de chamadas de rede mockadas garantindo previsibilidade. Toda a esteira está configurada com GitHub Actions (CI/CD).",
        code: `import { test, expect } from '@playwright/test';\nimport { MoviesPage } from '../pages/MoviesPage';\n\ntest.describe('Validação de Cadastro', () => {\n  test('Deve cadastrar e validar no banco', async ({ page, request }) => {\n    const moviesPage = new MoviesPage(page);\n    await moviesPage.navigate();\n    await moviesPage.submitMovie('O Farofeiro 2', 'Comédia', '2026');\n    \n    const response = await page.waitForResponse('**/api/movies');\n    expect(response.status()).toBe(201);\n  });\n});`,
        repo: "https://github.com/DouglasAntoni0/playwrightcomplete",
        visualClass: "playwright-bg",
        iconClass: "ph-browsers",
        reverseBorder: false
    },
    {
        id: "modal-4",
        number: "04",
        category: "main",
        title: "QAx-Mobile: Automação Android",
        summary: "Framework de testes automatizados para aplicações Mobile usando Appium.",
        tags: ["Appium", "WebdriverIO", "Robot Framework", "Mobile"],
        tools: ["Appium", "WebdriverIO", "Robot Framework", "MongoDB", "Android Studio"],
        desc: "Projeto completo de automação mobile para testes ponta a ponta (E2E) em aplicativos Android nativos (Yodapp e MarkX).<br><br>A arquitetura foi desenvolvida explorando duas frentes: uma com <strong>WebdriverIO (JavaScript)</strong> e outra com <strong>Robot Framework (Python)</strong>. O framework lida com interações nativas complexas (swipes, taps, manipulação de UI) e integra scripts em Python para limpar e popular a base de dados no MongoDB antes das execuções, garantindo a idoneidade da massa de testes.",
        code: `describe('Tarefas', () => {\n  it('deve cadastrar uma nova tarefa', async () => {\n    await loginScreen.doLogin('admin', 'qaninja')\n    await tasksScreen.create('Estudar Appium e Maestro')\n    await expect(await tasksScreen.taskName('Estudar Appium')).toBeDisplayed()\n  })\n})`,
        repo: "https://github.com/DouglasAntoni0/QAx-Mobile",
        visualClass: "mobile-bg",
        iconClass: "ph-device-mobile",
        reverseBorder: true
    },
    {
        id: "modal-5",
        number: "05",
        category: "main",
        title: "QA Automaton IA: Self-Healing",
        summary: "Playwright + GPT-4 para Self-Healing e Geração de Dados.",
        tags: ["Playwright", "OpenAI", "TypeScript"],
        tools: ["Playwright", "TypeScript", "OpenAI API", "GitHub Actions"],
        desc: "Projeto experimental de vanguarda unindo Inteligência Artificial a testes E2E. O framework utiliza TypeScript e Playwright integrado à API da OpenAI para duas frentes inovadoras: geração dinâmica de massa de dados sintéticos e um mecanismo de 'Self-Healing'. Quando a automação falha por um locator quebrado na UI, a IA analisa o DOM em tempo real e encontra o novo seletor correspondente, permitindo que o teste continue sem interrupções.",
        code: `import { test, expect } from '@playwright/test';\nimport { getHealedLocator } from '../support/self-healing/locator';\n\ntest('Deve curar locator quebrado via IA', async ({ page }) => {\n  const brokenLocator = '#old-btn-submit';\n  const targetDesc = 'Botão de confirmar cadastro';\n  \n  // A IA analisa o DOM e retorna o novo locator corrigido\n  const healedLocator = await getHealedLocator(page, brokenLocator, targetDesc);\n  \n  await page.locator(healedLocator).click();\n  await expect(page.locator('.success-msg')).toBeVisible();\n});`,
        repo: "https://github.com/DouglasAntoni0/automacao-inteligente-qa",
        visualClass: "ai-bg",
        iconClass: "ph-brain",
        reverseBorder: false
    },
    {
        id: "modal-6",
        number: "06",
        category: "main",
        title: "Multi-Framework QA: Dogfooding",
        summary: "Cobertura de testes do próprio site com 4 frameworks distintos.",
        tags: ["Cypress", "Playwright", "Robot", "Selenium"],
        tools: ["Cypress", "Playwright", "Robot Framework", "Selenium", "Node.js", "Python"],
        desc: "Aplicando o conceito de 'Dogfooding', desenvolvi uma suíte completa de testes E2E para garantir a qualidade visual e funcional deste próprio portfólio. Para demonstrar proficiência nas principais tecnologias do mercado, a automação foi escrita simultaneamente em 4 frameworks diferentes: Cypress, Playwright, Robot Framework e Selenium WebDriver. Os scripts validam a responsividade, o comportamento do Glassmorphism e a lógica de abertura dos modais.",
        code: `*** Settings ***\nLibrary    SeleniumLibrary\n\n*** Test Cases ***\nValidar Abertura de Modais de Projetos\n    Open Browser    https://douglasqa.netlify.app    chrome\n    Wait Until Element Is Visible    css=.project-row\n    Click Element    css=.trigger-modal[data-modal="modal-1"]\n    Wait Until Element Is Visible    css=.glass-modal.active\n    Sleep    1s\n    Click Element    css=.close-modal\n    Close Browser`,
        repo: "https://github.com/DouglasAntoni0/site-pessoal",
        visualClass: "multi-bg",
        iconClass: "ph-check-square-offset",
        reverseBorder: true
    },
    {
        id: "modal-7",
        number: "07",
        category: "main",
        title: "Pytest: Gerenciador de Tarefas",
        summary: "Suíte completa de testes para aplicação Python/Flask.",
        tags: ["Pytest", "Python", "Flask"],
        tools: ["Pytest", "Flask", "Playwright", "GitHub Actions"],
        desc: "Suíte profissional de testes para um gerenciador de tarefas em Python, cobrindo desde a regra de domínio até fluxos de ponta a ponta. A arquitetura combina fixtures em camadas, testes parametrizados e validações de CRUD, regras de negócio, serialização e persistência JSON.<br><br>O projeto também valida uma API Flask com test client, exercita páginas HTML com Playwright em navegador real e mantém a execução em GitHub Actions. O foco é demonstrar cobertura ampla, clareza de cenários, tratamento de casos extremos e confiança para evoluir a aplicação sem regressões.",
        code: `import pytest\nfrom task_manager.models import Tarefa, Status\n\n@pytest.mark.parametrize('status_destino', [\n    Status.EM_ANDAMENTO,\n    Status.CONCLUIDA,\n    Status.ARQUIVADA,\n])\ndef test_transicao_de_status_valida(status_destino):\n    tarefa = Tarefa(titulo='Validar fluxo crítico')\n\n    tarefa.alterar_status(status_destino)\n\n    assert tarefa.status == status_destino`,
        repo: "https://github.com/DouglasAntoni0/pytest",
        visualClass: "pytest-bg",
        iconClass: "ph-check-square-offset",
        reverseBorder: false
    },
    {
        id: "modal-8",
        number: "08",
        category: "main",
        title: "Selenium JS Toolshop QA",
        summary: "Automação web E2E com Selenium puro em JavaScript.",
        tags: ["Selenium", "JavaScript", "Mocha"],
        tools: ["Selenium WebDriver", "Mocha", "Chai", "Faker", "Mochawesome"],
        desc: "Projeto de automação web criado do zero com Selenium WebDriver puro em JavaScript para a plataforma Practice Software Testing Toolshop. A suíte cobre fluxos realistas de e-commerce, incluindo login, cadastro, busca, carrinho, checkout, pagamento e contato.<br><br>A arquitetura usa Page Object Model, seletores centralizados, massa dinâmica com Faker e apoio de API pública para preparar dados antes da execução. As esperas são explícitas e orientadas a sinais reais da interface, com relatórios Mochawesome e pipeline em GitHub Actions para manter execução reproduzível.",
        code: `describe('Checkout como convidado', () => {\n  it('deve finalizar compra com valor correto', async () => {\n    await catalogPage.searchProduct('hammer');\n    await productPage.addToCart();\n    await cartPage.updateQuantity(2);\n\n    expect(await cartPage.total()).to.equal(expectedTotal);\n    await checkoutPage.finishAsGuest(testData.customer);\n    expect(await orderPage.successMessage()).to.contain('Payment was successful');\n  });\n});`,
        repo: "https://github.com/DouglasAntoni0/selenium",
        visualClass: "selenium-bg",
        iconClass: "ph-browsers",
        reverseBorder: true
    },
    {
        id: "modal-9",
        number: "09",
        category: "main",
        title: "BDD com Cucumber | Starbugs Coffee",
        summary: "Cenários BDD em português para jornada de compra.",
        tags: ["Cucumber", "Ruby", "BDD"],
        tools: ["Ruby", "Cucumber", "Capybara", "Selenium", "GitHub Actions"],
        desc: "Projeto de automação E2E para a aplicação Starbugs Coffee, construído com Ruby, Cucumber, Capybara e Selenium WebDriver. Os cenários são escritos em Gherkin em português para documentar o comportamento esperado do produto de forma clara para negócio, QA e desenvolvimento.<br><br>A base usa Page Object para separar ações de tela dos steps, reduzindo duplicação e facilitando manutenção. A cobertura inclui catálogo, pedidos, endereço, pagamento, confirmação de compra e regras de cupons válidos, expirados e inválidos, com execução preparada para CI/CD no GitHub Actions.",
        code: `Cenário: Comprar café com cupom válido\n  Dado que acesso a loja Starbugs\n  Quando escolho o produto "Expresso Gelado"\n  E informo o cupom "MEUCAFE"\n  E finalizo o pedido com pagamento PIX\n  Então devo ver a confirmação da compra\n  E o desconto deve ser aplicado no total`,
        repo: "https://github.com/DouglasAntoni0/BDD-cucumber",
        visualClass: "bdd-bg",
        iconClass: "ph-flow-arrow",
        reverseBorder: false
    },
    {
        id: "modal-10",
        number: "10",
        category: "volunteer",
        title: "SouJunior: Automação Open Source",
        summary: "Testes E2E garantindo a qualidade da plataforma da ONG SouJunior.",
        tags: ["Playwright", "Cypress", "Voluntariado", "Open Source"],
        tools: ["Playwright", "Cypress", "GitHub Actions", "QA Social"],
        desc: "Atuação direta como Software Quality Engineer voluntário na ONG SouJunior. Este projeto concentra a suíte de testes E2E desenvolvida para garantir a estabilidade e confiabilidade da plataforma utilizada por profissionais de tecnologia.<br><br>A arquitetura de qualidade contempla scripts robustos criados tanto em <strong>Cypress</strong> quanto em <strong>Playwright</strong>, cobrindo fluxos críticos de negócio como cadastro, listagem de iniciativas e depoimentos, rodando de forma contínua em pipelines de CI/CD para assegurar o conceito de 'Zero Falhas' no ambiente de impacto social.",
        code: `import { test, expect } from '@playwright/test';\n\ntest.describe('Iniciativas - SouJunior', () => {\n  test('Deve carregar a página com sucesso', async ({ page }) => {\n    await page.goto('/iniciativas');\n    \n    const title = page.locator('h1');\n    await expect(title).toContainText('Nossas Iniciativas');\n    \n    const cards = page.locator('.iniciativa-card');\n    await expect(cards.first()).toBeVisible();\n  });\n});`,
        repo: "https://github.com/DouglasAntoni0/Testes-E2E-SouJunior",
        visualClass: "volunteer-bg",
        iconClass: "ph-heart",
        reverseBorder: true
    }
];
